services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gis_service_app
    restart: always
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - "3620:3620"
    networks:
      - global-network-geosandbox

networks:
  global-network-geosandbox:
    external: true