services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gis_service_app
    restart: always
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - "3620:3620"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: gis_service_db
    restart: always
    user: postgres
    secrets:
      - db-password
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_gis_geosandbox
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "5433:5433"
    expose:
      - "5433"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db_gis_geosandbox" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
